### ISSUE TITLE
FR: Ultimachine Einsy Temp

### ISSUE THREAD

**Issue by kickhad** [imrahil/OctoPrint-NavbarTemp#39] opened 2018-10-15 15:31 UTC
Would be great if there was an option to get the Einsy Rambo temp on the Navbar. I keep my RPi outside the enclosure, the Einsy is in.

**Comment by Cosik** [comment] 2018-10-15 15:54
@kickhad I see some problems:
1. Have no Einsy Rambo for testing
2. Have no idea how to get information about temperature.
3. There are PR which are not merged to master

**Comment by kickhad** [comment] 2019-01-10 15:17
I'm not sure it is parsed into the OctoPrint datamodel.

**Comment by Cosik** [comment] 2020-03-14 15:20
@kickhad is this feature still valid?

**Comment by arekm** [comment] 2022-08-16 20:41
Duplicate of https://github.com/imrahil/OctoPrint-NavbarTemp/issues/87 (which is newer but has more info about obtaining einsy board temperature, so closing this one).

**Closed as completed by arekm** 2022-08-16 20:41 UTC
Labels: more info needed
