### ISSUE TITLE
Wrong name for RPi3 on NavbarTemp

### ISSUE THREAD

**Issue by phcoetzee** [imrahil/OctoPrint-NavbarTemp#43] opened 2018-10-16 15:04 UTC
NavbarTemp used to show the prefix to temp for my RPi3 as Raspi, but today after the update it show the prefix temp as SoC. The temp percentage is correct its just showing: SoC: 35.4°C instead of Raspi: 35.4°C

**Comment by Cosik** [comment] 2018-10-16 15:55
@phcoetzee it's not a bug. We change displayed name to general name.

**Comment by phcoetzee** [comment] 2018-10-16 16:00
Thx, but how can I change Soc to Raspi?

**Comment by imrahil** [comment] 2018-10-16 16:22
@cosik can we configure displayed name via settings?

**Comment by phcoetzee** [comment] 2018-10-16 16:26
No option to change display name via settings but it would be a nice option please!

**Comment by Cosik** [comment] 2018-10-16 17:08
@phcoetzee adn @imrahil ofc, we could try to do this, but this should be next feature called something like "custom names in NavbarTemp". There is probably some other FR for that.

**Comment by phcoetzee** [comment] 2018-10-16 17:11
Yes please! :+1:

**Comment by SillyHats** [comment] 2018-12-01 16:57
This would be a good option to add to the settings

**Comment by Cosik** [comment] 2020-03-18 16:07
@phcoetzee and @SillyHats I added such possibility. Please check latest devel and let me know if it's working correctly.

**Comment by phcoetzee** [comment] 2020-03-18 16:38
If I add the name Raspi in the Name Configuration for custom commands it reads:
SoC: 34.3°C Raspi: null in the Navbar so I guess something not right?

**Comment by Cosik** [comment] 2020-03-18 17:45
@phcoetzee are you sure that you have installed plugin from devel branch and you have clean cache of web browser?

**Comment by phcoetzee** [comment] 2020-03-19 12:16
Sorry I have installed the master. I have now installed the devel and its now working perfectly showing custom name. Thank you for your effort.

**Comment by Cosik** [comment] 2020-03-19 16:20
@phcoetzee change will be in official release 0.14 which should be available soon.

**Closed as completed by Cosik** 2020-03-19 16:20 UTC
Labels: enhancement
